// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrbitMap.Domain.Persistent;

#nullable disable

namespace OrbitMap.Domain.Persistent.Migrations
{
    [DbContext(typeof(OrbitMapContext))]
    [Migration("20250108044138_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitMap.Domain.Entities.Connection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConnectionId");

                    b.HasIndex("GroupName");

                    b.ToTable("Connection");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendship");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7dc0741b-b5b4-4b3e-808d-1da4524169ed"),
                            AddresseeId = new Guid("cacf40b2-772b-4c20-a0c9-cd7359353622"),
                            CreatedDate = new DateTime(2025, 1, 8, 11, 41, 38, 621, DateTimeKind.Local).AddTicks(1070),
                            RequesterId = new Guid("b1cc911f-7d57-4043-a716-c5249da61270"),
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Group", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.LastMessageChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MessageLastDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("LastMessageChat");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.PlayerIds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerIds");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3516c2f0-7f9f-4a5d-9ec0-ee5696c95bb1"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1cc911f-7d57-4043-a716-c5249da61270"),
                            Birthday = new DateOnly(2003, 12, 8),
                            CreatedDate = new DateTime(2025, 1, 8, 11, 41, 38, 624, DateTimeKind.Local).AddTicks(1210),
                            DisplayName = "admin",
                            IsPremium = true,
                            LastActive = new DateTime(2025, 1, 8, 11, 41, 38, 624, DateTimeKind.Local).AddTicks(1210),
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PhoneNumber = "0123456789",
                            RoleId = new Guid("3516c2f0-7f9f-4a5d-9ec0-ee5696c95bb1"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("cacf40b2-772b-4c20-a0c9-cd7359353622"),
                            Birthday = new DateOnly(2003, 12, 8),
                            CreatedDate = new DateTime(2025, 1, 8, 11, 41, 38, 624, DateTimeKind.Local).AddTicks(1330),
                            DisplayName = "khoa",
                            IsPremium = true,
                            LastActive = new DateTime(2025, 1, 8, 11, 41, 38, 624, DateTimeKind.Local).AddTicks(1330),
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PhoneNumber = "1234567890",
                            RoleId = new Guid("3516c2f0-7f9f-4a5d-9ec0-ee5696c95bb1"),
                            Username = "khoa"
                        },
                        new
                        {
                            Id = new Guid("68c029f3-b49f-41da-864c-40299f71a956"),
                            Birthday = new DateOnly(2003, 12, 8),
                            CreatedDate = new DateTime(2025, 1, 8, 11, 41, 38, 624, DateTimeKind.Local).AddTicks(1340),
                            DisplayName = "hoang",
                            IsPremium = true,
                            LastActive = new DateTime(2025, 1, 8, 11, 41, 38, 624, DateTimeKind.Local).AddTicks(1350),
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PhoneNumber = "0399533724",
                            RoleId = new Guid("3516c2f0-7f9f-4a5d-9ec0-ee5696c95bb1"),
                            Username = "hoang"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Connection", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Group", "Group")
                        .WithMany("Connections")
                        .HasForeignKey("GroupName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.User", "Addressee")
                        .WithMany("FriendshipAddressees")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.User", "Requester")
                        .WithMany("FriendshipRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.LastMessageChat", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.User", "Recipient")
                        .WithMany("LastMessageChatsReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.User", "Sender")
                        .WithMany("LastMessageChatsSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Message", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.User", "Recipient")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.PlayerIds", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.User", "User")
                        .WithMany("PlayerIds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.User", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Group", b =>
                {
                    b.Navigation("Connections");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.User", b =>
                {
                    b.Navigation("FriendshipAddressees");

                    b.Navigation("FriendshipRequests");

                    b.Navigation("LastMessageChatsReceived");

                    b.Navigation("LastMessageChatsSent");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("PlayerIds");
                });
#pragma warning restore 612, 618
        }
    }
}
