// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrbitMap.Domain.Persistent;

#nullable disable

namespace OrbitMap.Domain.Persistent.Migrations
{
    [DbContext(typeof(OrbitMapContext))]
    [Migration("20250217160223_Config_DateOnly_For_Birthday")]
    partial class Config_DateOnly_For_Birthday
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrbitMap.Domain.Entities.BusinessService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BusinessService");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc9862b5-6328-44fe-acf9-d5def2c5ea29"),
                            BusinessServiceType = "FIRST_RESANDHOTEL",
                            Price = 299000
                        },
                        new
                        {
                            Id = new Guid("50cd0e88-e256-424b-b694-bdfe52d40bab"),
                            BusinessServiceType = "RESANDHOTEL_1Y",
                            Price = 1299000
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Connection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConnectionId");

                    b.HasIndex("GroupName");

                    b.ToTable("Connection");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendship");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7dc0741b-b5b4-4b3e-808d-1da4524169ed"),
                            AddresseeId = new Guid("cacf40b2-772b-4c20-a0c9-cd7359353622"),
                            CreatedDate = new DateTime(2025, 2, 17, 16, 2, 23, 336, DateTimeKind.Utc).AddTicks(5210),
                            RequesterId = new Guid("b1cc911f-7d57-4043-a716-c5249da61270"),
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Group", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.LastMessageChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastMessageChatDocument")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("LastMessageChat");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Location");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.MemberLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberLocation");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MessageDocument")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BannerImage")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BusinessImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<string>>("ImageUrls")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsefulReactionCount")
                        .HasColumnType("integer");

                    b.Property<int>("UselessReactionCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8254d0a9-6b2b-41e4-ac19-d56be30a5727"),
                            BannerImage = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783633/3b07c90d-3c5c-4600-a569-274d93804790.png",
                            BusinessAddress = "Thái Bình",
                            BusinessImage = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783632/2828588e-984c-47fe-acdd-77eca703c9d3.png",
                            BusinessName = "Báo Thái Bình",
                            Content = "Bảo tàng tại Nam Từ Liêm, Hà Nội, mở cửa 1/11 và miễn phí vé trong tháng đầu. Dự án 2.500 tỷ đồng trải rộng trên 74ha, với điểm nhấn là Tháp Chiến thắng cao 45m - tượng trưng cho năm 1945. Ngoài trưng bày lịch sử chiến tranh, bảo tàng còn mang đến trải nghiệm về cuộc đấu tranh của Quân đội Nhân dân Việt Nam.",
                            CreatedDate = new DateTime(2025, 2, 17, 16, 2, 23, 337, DateTimeKind.Utc).AddTicks(3890),
                            ExpirationDate = new DateTime(2025, 3, 17, 16, 2, 23, 337, DateTimeKind.Utc).AddTicks(3900),
                            ImageUrls = new List<string> { "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783634/4fa1560a-245a-414c-a2ba-ed6ab02368a2.png" },
                            Title = "TỪ 1/11 BẢO TÀNG LỊCH SỬ QUÂN SỰ MIỄN PHÍ VÉ",
                            Type = "HeaderBanner",
                            UsefulReactionCount = 0,
                            UselessReactionCount = 0
                        },
                        new
                        {
                            Id = new Guid("fc456c95-6ffe-4408-a64e-1750c96e38a0"),
                            BusinessAddress = "Hà Nội",
                            BusinessImage = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783632/2828588e-984c-47fe-acdd-77eca703c9d3.png",
                            BusinessName = "Viettrekking",
                            Content = "Fansipan – ngọn núi cao nhất Việt Nam, không chỉ được mệnh danh là Nóc nhà Đông Dương mà còn là biểu tượng chinh phục của sức trẻ cùng lòng quyết tâm cháy bỏng. Với độ cao 3143m, Fansipan là ngọn núi cao nhất Việt Nam và là mơ ước của những người đam mê chinh phục.",
                            CreatedDate = new DateTime(2025, 2, 17, 16, 2, 23, 337, DateTimeKind.Utc).AddTicks(3910),
                            ExpirationDate = new DateTime(2025, 3, 17, 16, 2, 23, 337, DateTimeKind.Utc).AddTicks(3910),
                            ImageUrls = new List<string> { "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783634/4fa1560a-245a-414c-a2ba-ed6ab02368a2.png" },
                            Title = "Tour leo núi Fansipan 2N1Đ (Xuất phát từ Sa Pa)",
                            Type = "BannersOnPage",
                            UsefulReactionCount = 0,
                            UselessReactionCount = 0
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.NewsReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsReaction");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3516c2f0-7f9f-4a5d-9ec0-ee5696c95bb1"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Name = "Member"
                        },
                        new
                        {
                            Id = new Guid("3fd223f6-3edd-4c87-888a-35defcff39e8"),
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Weather")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Story");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.SubscriptionIds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("SubscriptionIds");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcd34cfc-02e3-430c-93d1-a4943e10293a"),
                            AvatarUrl = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736499707/ad62b614-4cb7-4e59-af56-ebd47319cf6b.jpg",
                            CreatedDate = new DateTime(2025, 2, 17, 16, 2, 23, 338, DateTimeKind.Utc).AddTicks(1720),
                            DisplayName = "admin",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PhoneNumber = "8123456789",
                            RoleId = new Guid("3516c2f0-7f9f-4a5d-9ec0-ee5696c95bb1"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Business", b =>
                {
                    b.HasBaseType("OrbitMap.Domain.Entities.User");

                    b.Property<Guid>("BusinessServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("BusinessType")
                        .HasColumnType("integer");

                    b.HasIndex("BusinessServiceId");

                    b.HasDiscriminator().HasValue("Business");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Member", b =>
                {
                    b.HasBaseType("OrbitMap.Domain.Entities.User");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ExpiredRankDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp without time zone");

                    b.HasDiscriminator().HasValue("Member");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1cc911f-7d57-4043-a716-c5249da61270"),
                            AvatarUrl = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736499707/ad62b614-4cb7-4e59-af56-ebd47319cf6b.jpg",
                            CreatedDate = new DateTime(2025, 2, 17, 16, 2, 23, 336, DateTimeKind.Utc).AddTicks(9830),
                            DisplayName = "Khoa Gió Tai",
                            PasswordHash = "v6plobem2ptzJLRd532mc835oAiq5JhrqBgHaCbjR+Y=",
                            PhoneNumber = "0123456789",
                            RoleId = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Username = "khoa",
                            Birthday = new DateOnly(1999, 1, 1),
                            IsPremium = true,
                            LastActive = new DateTime(2025, 2, 17, 16, 2, 23, 336, DateTimeKind.Utc).AddTicks(9560)
                        },
                        new
                        {
                            Id = new Guid("cacf40b2-772b-4c20-a0c9-cd7359353622"),
                            AvatarUrl = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736250368/fc72a64e-91fd-495b-bf19-b0f9ae97f1cc.png",
                            CreatedDate = new DateTime(2025, 2, 17, 16, 2, 23, 336, DateTimeKind.Utc).AddTicks(9960),
                            DisplayName = "Hoàng Gió Nhải",
                            PasswordHash = "Jwcj5/UKJtSukNoOEwefKT3TfplT9/mAHOfeGaNfxY4=",
                            PhoneNumber = "1234567890",
                            RoleId = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Username = "hoang",
                            Birthday = new DateOnly(1999, 1, 1),
                            IsPremium = true,
                            LastActive = new DateTime(2025, 2, 17, 16, 2, 23, 336, DateTimeKind.Utc).AddTicks(9950)
                        },
                        new
                        {
                            Id = new Guid("68c029f3-b49f-41da-864c-40299f71a956"),
                            AvatarUrl = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736250368/fc72a64e-91fd-495b-bf19-b0f9ae97f1cc.png",
                            CreatedDate = new DateTime(2025, 2, 17, 16, 2, 23, 336, DateTimeKind.Utc).AddTicks(9990),
                            DisplayName = "quan",
                            PasswordHash = "e24ih8ftxem8WzOQkrSS/q4n7Yv3+eGp9GlZThzEFcs=",
                            PhoneNumber = "0399533724",
                            RoleId = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Username = "quan",
                            Birthday = new DateOnly(1999, 1, 1),
                            IsPremium = true,
                            LastActive = new DateTime(2025, 2, 17, 16, 2, 23, 336, DateTimeKind.Utc).AddTicks(9970)
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Connection", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Group", "Group")
                        .WithMany("Connections")
                        .HasForeignKey("GroupName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Addressee")
                        .WithMany("FriendshipAddressees")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.Member", "Requester")
                        .WithMany("FriendshipRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.MemberLocation", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Location", "Location")
                        .WithMany("MemberLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.Member", "Member")
                        .WithMany("MemberLocations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.NewsReaction", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Member")
                        .WithMany("NewsReactions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.News", "News")
                        .WithMany("NewsReactions")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("News");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Story", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Member")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.SubscriptionIds", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Member")
                        .WithMany("SubscriptionIds")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Member")
                        .WithMany("Transactions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.User", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Business", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.BusinessService", "BusinessService")
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessService");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.BusinessService", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Group", b =>
                {
                    b.Navigation("Connections");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Location", b =>
                {
                    b.Navigation("MemberLocations");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.News", b =>
                {
                    b.Navigation("NewsReactions");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Member", b =>
                {
                    b.Navigation("FriendshipAddressees");

                    b.Navigation("FriendshipRequests");

                    b.Navigation("MemberLocations");

                    b.Navigation("NewsReactions");

                    b.Navigation("Stories");

                    b.Navigation("SubscriptionIds");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
