// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrbitMap.Domain.Persistent;

#nullable disable

namespace OrbitMap.Domain.Persistent.Migrations
{
    [DbContext(typeof(OrbitMapContext))]
    partial class OrbitMapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitMap.Domain.Entities.BusinessService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BusinessService");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dbce667-1f48-4cf5-a07a-35fd8e8c1769"),
                            BusinessServiceType = "FIRST_RESANDHOTEL",
                            Price = 299000m
                        },
                        new
                        {
                            Id = new Guid("9b04d57e-61bf-4cb6-b9db-7e97bb5bbc9b"),
                            BusinessServiceType = "RESANDHOTEL_1Y",
                            Price = 1299000m
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Connection", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConnectionId");

                    b.HasIndex("GroupName");

                    b.ToTable("Connection");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendship");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7dc0741b-b5b4-4b3e-808d-1da4524169ed"),
                            AddresseeId = new Guid("cacf40b2-772b-4c20-a0c9-cd7359353622"),
                            CreatedDate = new DateTime(2025, 1, 14, 10, 4, 47, 487, DateTimeKind.Local).AddTicks(2290),
                            RequesterId = new Guid("b1cc911f-7d57-4043-a716-c5249da61270"),
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Group", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.LastMessageChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MessageLastDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("LastMessageChat");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.HasIndex("StoryId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BannerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsefulReactionCount")
                        .HasColumnType("int");

                    b.Property<int>("UselessReactionCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8254d0a9-6b2b-41e4-ac19-d56be30a5727"),
                            BannerImage = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783633/3b07c90d-3c5c-4600-a569-274d93804790.png",
                            BusinessAddress = "Thái Bình",
                            BusinessImage = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783632/2828588e-984c-47fe-acdd-77eca703c9d3.png",
                            BusinessName = "Báo Thái Bình",
                            Content = "Bảo tàng tại Nam Từ Liêm, Hà Nội, mở cửa 1/11 và miễn phí vé trong tháng đầu. Dự án 2.500 tỷ đồng trải rộng trên 74ha, với điểm nhấn là Tháp Chiến thắng cao 45m - tượng trưng cho năm 1945. Ngoài trưng bày lịch sử chiến tranh, bảo tàng còn mang đến trải nghiệm về cuộc đấu tranh của Quân đội Nhân dân Việt Nam.",
                            CreatedDate = new DateTime(2025, 1, 14, 3, 4, 47, 490, DateTimeKind.Utc).AddTicks(5930),
                            ExpirationDate = new DateTime(2025, 2, 14, 3, 4, 47, 490, DateTimeKind.Utc).AddTicks(5930),
                            ImageUrls = "[\"https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783634/4fa1560a-245a-414c-a2ba-ed6ab02368a2.png\"]",
                            Title = "TỪ 1/11 BẢO TÀNG LỊCH SỬ QUÂN SỰ MIỄN PHÍ VÉ",
                            Type = "HeaderBanner",
                            UsefulReactionCount = 0,
                            UselessReactionCount = 0
                        },
                        new
                        {
                            Id = new Guid("fc456c95-6ffe-4408-a64e-1750c96e38a0"),
                            BusinessAddress = "Hà Nội",
                            BusinessImage = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783632/2828588e-984c-47fe-acdd-77eca703c9d3.png",
                            BusinessName = "Viettrekking",
                            Content = "Fansipan – ngọn núi cao nhất Việt Nam, không chỉ được mệnh danh là Nóc nhà Đông Dương mà còn là biểu tượng chinh phục của sức trẻ cùng lòng quyết tâm cháy bỏng. Với độ cao 3143m, Fansipan là ngọn núi cao nhất Việt Nam và là mơ ước của những người đam mê chinh phục.",
                            CreatedDate = new DateTime(2025, 1, 14, 3, 4, 47, 490, DateTimeKind.Utc).AddTicks(5940),
                            ExpirationDate = new DateTime(2025, 2, 14, 3, 4, 47, 490, DateTimeKind.Utc).AddTicks(5940),
                            ImageUrls = "[\"https://res.cloudinary.com/dl1sfqrek/image/upload/v1736783634/4fa1560a-245a-414c-a2ba-ed6ab02368a2.png\"]",
                            Title = "Tour leo núi Fansipan 2N1Đ (Xuất phát từ Sa Pa)",
                            Type = "BannersOnPage",
                            UsefulReactionCount = 0,
                            UselessReactionCount = 0
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.NewsReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsReaction");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.PlayerIds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("PlayerIds");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3516c2f0-7f9f-4a5d-9ec0-ee5696c95bb1"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Name = "Member"
                        },
                        new
                        {
                            Id = new Guid("3fd223f6-3edd-4c87-888a-35defcff39e8"),
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Weather")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Story");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcd34cfc-02e3-430c-93d1-a4943e10293a"),
                            AvatarUrl = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736499707/ad62b614-4cb7-4e59-af56-ebd47319cf6b.jpg",
                            CreatedDate = new DateTime(2025, 1, 14, 10, 4, 47, 491, DateTimeKind.Local).AddTicks(1060),
                            DisplayName = "admin",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            PhoneNumber = "8123456789",
                            RoleId = new Guid("3516c2f0-7f9f-4a5d-9ec0-ee5696c95bb1"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Business", b =>
                {
                    b.HasBaseType("OrbitMap.Domain.Entities.User");

                    b.Property<Guid>("BusinessServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("BusinessServiceId");

                    b.HasDiscriminator().HasValue("Business");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Member", b =>
                {
                    b.HasBaseType("OrbitMap.Domain.Entities.User");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ExpiredRankDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Member");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1cc911f-7d57-4043-a716-c5249da61270"),
                            AvatarUrl = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736499707/ad62b614-4cb7-4e59-af56-ebd47319cf6b.jpg",
                            CreatedDate = new DateTime(2025, 1, 14, 10, 4, 47, 488, DateTimeKind.Local).AddTicks(8750),
                            DisplayName = "Khoa Gió Tai",
                            PasswordHash = "v6plobem2ptzJLRd532mc835oAiq5JhrqBgHaCbjR+Y=",
                            PhoneNumber = "0123456789",
                            RoleId = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Username = "khoa",
                            Birthday = new DateOnly(1999, 1, 1),
                            IsPremium = true,
                            LastActive = new DateTime(2025, 1, 14, 10, 4, 47, 488, DateTimeKind.Local).AddTicks(8540)
                        },
                        new
                        {
                            Id = new Guid("cacf40b2-772b-4c20-a0c9-cd7359353622"),
                            AvatarUrl = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736250368/fc72a64e-91fd-495b-bf19-b0f9ae97f1cc.png",
                            CreatedDate = new DateTime(2025, 1, 14, 10, 4, 47, 488, DateTimeKind.Local).AddTicks(8870),
                            DisplayName = "Hoàng Gió Nhải",
                            PasswordHash = "Jwcj5/UKJtSukNoOEwefKT3TfplT9/mAHOfeGaNfxY4=",
                            PhoneNumber = "1234567890",
                            RoleId = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Username = "hoang",
                            Birthday = new DateOnly(1999, 1, 1),
                            IsPremium = true,
                            LastActive = new DateTime(2025, 1, 14, 10, 4, 47, 488, DateTimeKind.Local).AddTicks(8850)
                        },
                        new
                        {
                            Id = new Guid("68c029f3-b49f-41da-864c-40299f71a956"),
                            AvatarUrl = "https://res.cloudinary.com/dl1sfqrek/image/upload/v1736250368/fc72a64e-91fd-495b-bf19-b0f9ae97f1cc.png",
                            CreatedDate = new DateTime(2025, 1, 14, 10, 4, 47, 488, DateTimeKind.Local).AddTicks(8880),
                            DisplayName = "quan",
                            PasswordHash = "e24ih8ftxem8WzOQkrSS/q4n7Yv3+eGp9GlZThzEFcs=",
                            PhoneNumber = "0399533724",
                            RoleId = new Guid("d1cd3eef-3318-48e3-99f7-31a938fbd021"),
                            Username = "quan",
                            Birthday = new DateOnly(1999, 1, 1),
                            IsPremium = true,
                            LastActive = new DateTime(2025, 1, 14, 10, 4, 47, 488, DateTimeKind.Local).AddTicks(8880)
                        });
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Connection", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Group", "Group")
                        .WithMany("Connections")
                        .HasForeignKey("GroupName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Addressee")
                        .WithMany("FriendshipAddressees")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.Member", "Requester")
                        .WithMany("FriendshipRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.LastMessageChat", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Recipient")
                        .WithMany("LastMessageChatsReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.Member", "Sender")
                        .WithMany("LastMessageChatsSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Message", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Recipient")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.Member", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.News", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Business", null)
                        .WithMany("News")
                        .HasForeignKey("BusinessId");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.NewsReaction", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Member")
                        .WithMany("NewsReactions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitMap.Domain.Entities.News", "News")
                        .WithMany("NewsReactions")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("News");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.PlayerIds", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Member")
                        .WithMany("PlayerIds")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Story", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Member", "Member")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.User", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Business", b =>
                {
                    b.HasOne("OrbitMap.Domain.Entities.BusinessService", "BusinessService")
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessService");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.BusinessService", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Group", b =>
                {
                    b.Navigation("Connections");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.News", b =>
                {
                    b.Navigation("NewsReactions");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Business", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("OrbitMap.Domain.Entities.Member", b =>
                {
                    b.Navigation("FriendshipAddressees");

                    b.Navigation("FriendshipRequests");

                    b.Navigation("LastMessageChatsReceived");

                    b.Navigation("LastMessageChatsSent");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("NewsReactions");

                    b.Navigation("PlayerIds");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
